version: '3'
services:
  postgres:
    image: "postgres:alpine"
    restart: always
    environment:
      - TEST_USER=plm_test
      - TEST_PASSWORD=plm_test
      - TEST_DATABASE=plm_test
      - DEV_USER=plm
      - DEV_PASSWORD=plm
      - DEV_DATABASE=plm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d